# -*- coding: utf-8 -*-
"""ML Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YSdOmHD_MrvFfgTptXkUZMlgk8HQObFz

# Part 1
"""

modern_family = ['CLaiRe_DunPhY', 'PHiL_dUnpHY', 'GLoRiA_PriTCheTt', 'CaMErOn_TuCKEr', 'StELLa']

indices = []
characters = []

for indice, character in enumerate(modern_family):
  indices.append(indice)
  characters.append(character)

length = 5
for i in range(0, 5):
  
  # Lowercase
  characters[i] = characters[i].lower()

  # Replace
  characters[i] = characters[i].replace("_", "-")

# Function lambda
def func(s):
  return len(s)

# Creating required  list
temp = list(map(func, characters))

result_list = list(zip(indices, temp))

for i in list(result_list):
  indices[i[0]] = sum(i)
  
print(indices)

indices.sort(reverse =True)

zip_list = list(zip(indices, characters))
Phew_finally = dict(zip_list)

# Printing to check the output
# print(Phew_finally)

"""# Part 2"""

creepy_doll = ['red_light', 'green_light', 'red_light', 'you_got_shot', 'green_light', 'you_got_shot', 'you_got_shot', 'green_light',
               'you_ got_shot', 'red_light', 'green_light', 'red_light', 'you_got_shot', 'green_light','red_light', 'red_light', 
               'green_light', 'you_got_shot','red_light', 'you_got_shot']

next_game = []
next_game = creepy_doll[1:-3:3]

print(next_game)

"""# Part 3"""

class Titandex:

  def __init__(self, name, height, strength, win_streak = 0):

    self.name = name
    self.height = height
    self.strength = strength
    self.win_streak = win_streak
  
  def TitanvsScout(self, scout_name, scout_strength):
    
    if (self.strength > scout_strength):
      print(self.name, "wins!")
      self.win_streak += 1
    elif (self.strength < scout_strength):
      print(scout_name, "wins!")
      self.win_streak = 0
    else:
      print("Its a draw!")
  
  def TitanvsTitan(self, titan2):

    if (self.name == titan2.name):
      print("A titan cannot fight itself")

    elif (self.strength > titan2.strength):##
      self.win_streak +=1
      print(self.name, "wins!")
      titan2.win_streak = 0 
    else:
      titan2.win_streak +=1
      print(titan2.name, "wins!")
      self.win_streak = 0

founding_titan = Titandex('Founding Titan',13, 350, 0)
attack_titan = Titandex('Attack Titan', 15, 275)
armored_titan = Titandex('Armored Titan', 15, 250)
colossal_titan = Titandex('Colossal Titan', 60,300)
war_hammer_titan = Titandex('War Hammer Titan', 15, 235)
beast_titan = Titandex('Beast Titan', 17, 250)
cart_titan = Titandex('Cart Titan', 4, 175)
female_titan = Titandex('Female Titan', 14, 270)
jaw_titan = Titandex('Jaw Titan', 5, 225)

colossal_titan.TitanvsScout("Armin", 650)

print(colossal_titan.win_streak)

cart_titan.TitanvsTitan(female_titan)

print(cart_titan.win_streak)
print(female_titan.win_streak)